### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by tadas-subonis** [sn3d/lime-mvc#8]
I have noticed that code formatting is a mess... :/ Maybe atleast I could fix that with IDE by automatically indenting it and replaces tabs with spaces?

**Comment by sn3d** [comment]
Yeah it's messy because I used various computers, IDEs with different settings. Especially IntelliJIDEA does some weird space/tabs formatting. :( Feel free to reformat it. Sorry for my delayed responses but currently it's Christmas time. I saw you did also maven migration but I didn't check it yet :(

**Comment by tadas-subonis** [comment]
I'll look into that then. The main goal would be to remove tab indention, because it messes up indention among different IDEs x).

**Comment by sn3d** [comment]
solved in #9
